services:
  blitzquiz-server:
    container_name: blitzquiz-server
    image: ${SERVER_IMAGE:-ghcr.io/tommypreel/blitzquiz-server:latest}
    restart: always
    environment:
      - PORT=3650
    expose:
      - "3650"
    networks:
      - web

  blitzquiz-client:
    container_name: blitzquiz-client
    image: ${CLIENT_IMAGE:-ghcr.io/tommypreel/blitzquiz-client:latest}
    restart: always
    ports:
      - "3600:80"
    depends_on:
      - blitzquiz-server
    networks:
      - web

networks:
  web:
    external: true
    name: web
